name: "medallion_demo"
version: "1.0.0"
config-version: 2

profile: "medallion_demo"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medallion_demo:
    silver:
      +materialized: table
    gold:
      +materialized: table
