version: 2

models:
  - name: stg_silver__customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null

  - name: stg_silver__orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: order_total
        tests:
          - not_null
      - name: order_ts
        tests:
          - not_null

